#!/bin/bash
if [ "$#" -ne 2 -a "$#" -ne 3 ]; then
	echo "Usage: $0 <time> <priority> [filter]"
	echo
	echo "Time can be specified according to the specification in 'systemd.time(7)'."
	echo "Priority is the log levels as specified in 'journalctl(1)'."
	echo "Filter is a path to a file containing filtered regular expressions, one per line."

	exit 1
fi

time="$1"
priority="$2"
filter="$3"

if [ -z "$filter" ]; then
	filter="/dev/null"
fi

source /etc/default/logmail

journal=$(journalctl --since="$time" --priority="$priority" --no-pager --quiet | grep -v '^-- No entries --$' | grep -v -f "$filter" 2>&1)
units=$(systemctl --state=failed --no-pager --no-legend | grep -v -f "$filter" 2>&1)

message=""

if [ "${#journal}" -ne 0 ]; then
	message="$(printf "$message\n\nJournal Log\n-----------\n$journal")"
fi

if [ "${#units}" -ne 0 ]; then
	message="$(printf "$message\n\nFailed Units\n------------\n$units")"
fi

if [ "${#message}" -ne 0 ]; then
	message="$(printf "Details for $(hostname):$message")"

	sendmail -f "$mailfrom" "$mailto" <<EOF
From: $mailfrom
To: $mailto
Subject: $subject

$message
EOF
fi
